name: Executor
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        description: 'Execute program'
        default: 'Test'
        required: true
        type: string
jobs:
  execute:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Leetcode repository
      uses: actions/checkout@v2
      with:
        repository: jcdan3/devops
        token: ${{ secrets.GITHUB_TOKEN }}
        path: Leetcode
    - name: Execution
      run: python Leetcode/"${{ inputs.name }}"
      shell: sh
