name: Executor
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Execute Leetcode Solutions'
        default: 'backtrack/subsets.py'
        required: true
        type: string
jobs:
  execute-solution:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Leetcode repository
      uses: actions/checkout@main
      with:
        repository: vinoddalavai/Leetcode
        token: ${{ secrets.GITHUB_TOKEN }}
        path: Leetcode
    - name: Execution
      run: python Leetcode/"${{ inputs.name }}" -d
      shell: sh
